# -*- coding: utf-8 -*-
"""Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAKRgz55W_dEEPAgqhXawP9MZ0tFuIsd
"""

import pandas as pd
import numpy as np
# j'active l'IterativeImputer "expérimental" de sklearn
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_absolute_error, r2_score
import warnings

# Je coupe les warnings pour garder une sortie propre dans le terminal / notebook
warnings.filterwarnings("ignore")

def load_and_prepare_data(file_paths):
    """
    Charge la target (Y) et toutes les features (X1–X12),
    les aligne sur le même index trimestriel 'PeriodEndDate',
    sélectionne les bonnes colonnes et retourne un DataFrame fusionné.

    C'est ici que je standardise les noms des variables pour la suite du pipeline.
    """
    print("--- 1. Loading & Preparing Data ---")

    all_dfs = []

    # --- 1a. Target (Y) : Cost per Ton ---
    target_df = pd.read_csv(file_paths["target"], parse_dates=["QuarterEnd"])
    target_df = target_df.set_index("QuarterEnd")

    # Je renomme la colonne cible en Y_Cost_Per_Ton pour ne plus dépendre
    # du nom original dans le CSV.
    target_df = target_df.rename(columns={"Cost_Per_Ton": "Y_Cost_Per_Ton"})
    all_dfs.append(target_df)
    print(f"Loaded Target (Y): Y_Cost_Per_Ton from {file_paths['target']}")

    # --- 1b. Core features X1–X3 ---

    # X1 – Scrap PPI
    df_x1 = pd.read_csv(file_paths["X1"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x1 = df_x1[["PCU33123312"]].rename(columns={"PCU33123312": "X1_Scrap_Price"})
    all_dfs.append(df_x1)

    # X2 – Industrial electricity price
    df_x2 = pd.read_csv(file_paths["X2"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x2 = df_x2[["industrial cents per kilowatthour"]].rename(
        columns={"industrial cents per kilowatthour": "X2_Electricity_Price"}
    )
    all_dfs.append(df_x2)

    # X3 – Henry Hub natural gas
    df_x3 = pd.read_csv(file_paths["X3"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x3 = df_x3[
        ["Henry Hub Natural Gas Spot Price Dollars per Million Btu"]
    ].rename(
        columns={
            "Henry Hub Natural Gas Spot Price Dollars per Million Btu": "X3_Natural_Gas_Price"
        }
    )
    all_dfs.append(df_x3)

    print("Loaded Core Features: X1, X2, X3")

    # --- 1c. Advanced features X4–X12 ---

    # X4 – Diesel price (transport)
    df_x4 = pd.read_csv(file_paths["X4"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x4 = df_x4[
        ["U.S. No 2 Diesel Ultra Low Sulfur (0-15 ppm) Retail Prices Dollars per Gallon"]
    ].rename(
        columns={
            "U.S. No 2 Diesel Ultra Low Sulfur (0-15 ppm) Retail Prices Dollars per Gallon":
                "X4_Diesel_Price"
        }
    )
    all_dfs.append(df_x4)

    # X5 – Rail freight price
    df_x5 = pd.read_csv(file_paths["X5"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x5 = df_x5[["PCU48214821"]].rename(columns={"PCU48214821": "X5_Rail_Price"})
    all_dfs.append(df_x5)

    # X6 – Disaster cost (alt-data)
    df_x6 = pd.read_csv(file_paths["X6"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x6 = df_x6[["CPI-Adjusted Cost"]].rename(columns={"CPI-Adjusted Cost": "X6_Disaster_Cost"})
    all_dfs.append(df_x6)

    # X7 – Hourly wage (labour)
    df_x7 = pd.read_csv(file_paths["X7"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x7 = df_x7[["CES0500000003"]].rename(columns={"CES0500000003": "X7_Hourly_Wage"})
    all_dfs.append(df_x7)

    # X8 – US scrap exports
    df_x8 = pd.read_csv(file_paths["X8"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x8 = df_x8[["US_Scrap_Exports"]].rename(columns={"US_Scrap_Exports": "X8_Scrap_Exports"})
    all_dfs.append(df_x8)

    # X9 – Graphite electrode price
    df_x9 = pd.read_csv(file_paths["X9"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x9 = df_x9[["PCU3359913359910"]].rename(
        columns={"PCU3359913359910": "X9_Graphite_Price"}
    )
    all_dfs.append(df_x9)

    # X10 – All commodities PPI (proxy Pig Iron)
    df_x10 = pd.read_csv(file_paths["X10_proxy"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x10 = df_x10[["PPIACO"]].rename(columns={"PPIACO": "X10_All_Commodities"})
    all_dfs.append(df_x10)

    # X11 – US dollar index
    df_x11 = pd.read_csv(file_paths["X11"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x11 = df_x11[["DTWEXBGS"]].rename(columns={"DTWEXBGS": "X11_USD_Index"})
    all_dfs.append(df_x11)

    # X12 – Economic policy uncertainty
    df_x12 = pd.read_csv(file_paths["X12"], parse_dates=["QuarterEnd"]).set_index("QuarterEnd")
    df_x12 = df_x12[["News_Based_Policy_Uncert_Index"]].rename(
        columns={"News_Based_Policy_Uncert_Index": "X12_Econ_Uncertainty"}
    )
    all_dfs.append(df_x12)

    print("Loaded Advanced Features: X4–X12")

    # --- 1d. Fusion sur l'index trimestriel ---

    data = pd.concat(all_dfs, axis=1).sort_index()

    # Je supprime les lignes où la target est manquante.
    data_cleaned = data.dropna(subset=["Y_Cost_Per_Ton"])

    print(f"\nOriginal data shape (with missing Y): {data.shape}")
    print(f"Data shape after dropping missing Y:   {data_cleaned.shape}")

    return data_cleaned


def handle_missing_features(data, target_col="Y_Cost_Per_Ton"):
    """
    Impute les valeurs manquantes des features X avec IterativeImputer.
    Je laisse la cible Y intacte (je refuse de "fabriquer" le target).
    """
    print("\n--- 2. Handling Missing Feature Values ---")

    feature_cols = [c for c in data.columns if c != target_col]

    print("Missing values before imputation:")
    print(data[feature_cols].isna().sum())

    imputer = IterativeImputer(max_iter=10, random_state=42)
    features_imputed = imputer.fit_transform(data[feature_cols])

    features_imputed_df = pd.DataFrame(
        features_imputed,
        columns=feature_cols,
        index=data.index,
    )

    # Je recolle Y tel quel + les features imputées
    data_filled = pd.concat([data[[target_col]], features_imputed_df], axis=1)

    print("Missing values after imputation:")
    print(data_filled[feature_cols].isna().sum())

    return data_filled

def create_lagged_features(data, lag_periods, target_col="Y_Cost_Per_Ton"):
    """
    Crée les features décalées dans le temps (lags) pour toutes les colonnes X.

    Idée : pour prédire Y_t, je n'autorise que X_{t-1}, X_{t-2}, ...
    pour coller au fonctionnement réel (stocks / contrats).
    """
    print("\n--- 3. Engineering Lagged Features ---")

    feature_cols = [col for col in data.columns if col.startswith("X")]

    # Je travaille sur une copie pour ne pas modifier l'objet d'origine
    data_lagged = data.copy()

    for feature in feature_cols:
        for lag in lag_periods:
            col_name = f"{feature}_lag_{lag}Q"
            data_lagged[col_name] = data_lagged[feature].shift(lag)

    print(f"Created {len(feature_cols) * len(lag_periods)} lagged features.")

    # Je supprime les X non laggés pour ne pas "tricher" avec l'info du trimestre courant
    data_lagged = data_lagged.drop(columns=feature_cols)

    # Je coupe les premières lignes qui ont des NaN à cause des lags
    n_drop = max(lag_periods)
    final_data = data_lagged.iloc[n_drop:]

    print(f"Dropped first {n_drop} rows with incomplete lag information.")
    print(f"Final modelling dataset shape: {final_data.shape}")

    return final_data

def validate_model(X, y, model, n_splits=5):
    """
    Validation walk-forward avec TimeSeriesSplit.

    Je respecte la chronologie: les folds d'entraînement sont toujours
    antérieurs aux folds de test.
    """
    print(f"\n--- 4. Validating Model with TimeSeriesSplit (n_splits={n_splits}) ---")

    tscv = TimeSeriesSplit(n_splits=n_splits)

    mae_scores = []
    r2_scores = []

    for fold, (train_index, test_index) in enumerate(tscv.split(X), start=1):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        mae = mean_absolute_error(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)

        mae_scores.append(mae)
        r2_scores.append(r2)

        print(
            f"  Fold {fold}/{n_splits} | "
            f"Train: {len(y_train):3d} | Test: {len(y_test):3d} | "
            f"MAE: {mae:8.2f} | R²: {r2:6.3f}"
        )

    print("\n--- Cross-Validation Summary ---")
    print(f"Average MAE: {np.mean(mae_scores):.2f}")
    print(f"Average R²:  {np.mean(r2_scores):.3f}")

    return model

def get_feature_importance(model, X, y):
    """
    Entraîne le modèle sur tout le dataset et affiche le ranking
    des features les plus importantes.

    Ça me sert directement pour la partie "what drives Cost per Ton"
    dans le rapport.
    """
    print("\n--- 5. Training Final Model & Getting Feature Importance ---")

    model.fit(X, y)
    importances = model.feature_importances_

    feat_importance = (
        pd.Series(importances, index=X.columns)
        .sort_values(ascending=False)
    )

    print("\nTop 10 most important features:")
    print(feat_importance.head(10).to_string())

    return feat_importance

# --- Main execution ---------------------------------------------------------
if __name__ == "__main__":

    # 1. File paths centralisés (à adapter selon ton repo)
    file_paths = {
        # Target (Y)
        "target": "/content/nucor_04_METRICS_quarterly.csv",

        # Core features (X1–X3)
        "X1": "/content/PPI_Ferrous_Metal_Scrap_quarterly.csv",
        "X2": "/content/EIA_Electricity_Price_quarterly.csv",
        "X3": "/content/EIA_Natural_Gas_Price_quarterly.csv",

        # Advanced features (X4–X12)
        "X4": "/content/EIA_Diesel_Price_quarterly.csv",
        "X5": "/content/BLS_rail_price_quarterly.csv",
        "X6": "/content/NOAA_disasters_quarterly.csv",
        "X7": "/content/Hourly_Wage_quarterly.csv",
        "X8": "/content/US_Scrap_Exports_quarterly.csv",
        "X9": "/content/Graphite_Electrode_Price_quarterly.csv",
        "X10_proxy": "/content/PPI_All_Commodities_quarterly.csv",
        "X11": "/content/US_Dollar_Index_quarterly.csv",
        "X12": "/content/US_Policy_Uncertainty_quartely.csv",

        # Raw files (documentés mais non utilisés ici)
        #"unused_scrap": "Data/raw/PPI_Iron_Steel_Scrap_quarterly.csv",
        #"raw_01": "Data/raw/nucor_01_RAW_EXTRACT.csv",
        #"raw_02": "Data/raw/nucor_02_INCOME_STATEMENT.csv",
        #"raw_03": "Data/raw/nucor_03_BALANCE_SHEET.csv",
    }

    # 2. Chargement + merge
    data_cleaned = load_and_prepare_data(file_paths)

    # 3. Imputation des features manquantes
    data_filled = handle_missing_features(data_cleaned, target_col="Y_Cost_Per_Ton")

    # 4. Création des lags (1 à 4 trimestres)
    N_LAGS_Q = 4
    lag_periods = list(range(1, N_LAGS_Q + 1))
    data_final = create_lagged_features(data_filled, lag_periods, target_col="Y_Cost_Per_Ton")

    # 5. Split X / y
    y = data_final["Y_Cost_Per_Ton"]
    X = data_final.drop(columns=["Y_Cost_Per_Ton"])

    # 6. Toy model avec seulement les lags de X1–X3 (core drivers)
    core_features = [
        col for col in X.columns
        if col.startswith("X1_") or col.startswith("X2_") or col.startswith("X3_")
    ]
    X_core = X[core_features]

    print("\n--- 6a. Running 'Toy Model' (Core Features X1–X3) ---")
    rf_core = RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1,
    )
    validate_model(X_core, y, rf_core, n_splits=5)

    # 7. Modèle avancé avec toutes les features (X1–X12 lags)
    print("\n--- 6b. Running 'Advanced Model' (All Features X1–X12) ---")
    rf_full = RandomForestRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1,
    )
    final_model = validate_model(X, y, rf_full, n_splits=5)

    # 8. Feature importance sur le modèle complet
    feat_importance = get_feature_importance(final_model, X, y)

    print("\n--- Python Script Execution Complete ---")